name: Build Debug APK

on:
  workflow_dispatch: {}   # manual trigger
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
  uses: subosito/flutter-action@v2
  with:
    flutter-version: '3.35.2'   # ✅ set your Flutter version here
    channel: 'stable'


      - name: Install Dependencies
        working-directory: to_do_app
        run: flutter pub get

      - name: Build Debug APK
        working-directory: to_do_app
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: to_do_app/build/app/outputs/flutter-apk/app-debug.apk
